### PR TITLE
Add support for minitest

### LINKED ISSUE #9: Supporting Minitest?
I was looking for a plugin similar to [RubyTest for Sublime Text](https://github.com/maltize/sublime-text-2-ruby-tests) or [Atom RubyTest](https://github.com/moxley/atom-ruby-test) but to use within VSCode. Both of these seem to work fairly similarly but give some control over the type of test and commands being executed.

The biggest thing seems to be the fact that I don't use RSpec but instead the out of the box testing with Rails (ActiveSupport::TestCase, etc.) 

Have you given any thought to supporting anything other than RSpec?

### PR DESCRIPTION
**Pull request by tmandke**
Resolves #9

### CODE REVIEW

**Comment by iv-mexx** [comment]
Is there a way to use @tmandke's fork in VSCode until this is merged?

**Comment by tmandke** [comment]
I have stopped using VSCode 
To use my fork locally 
* Cloning my repo 
* symlink or copy it in the `~/.vscode/extension` [Reference](https://code.visualstudio.com/docs/extensions/example-hello-world#_installing-your-extension-locally)

**Comment by contentfree** [comment]
@noku Any chance of getting this merged in? Very useful for some of us.

**Comment by noku** [comment]
@tmandke thanks for PR

I have pushed a commit which makes the solution a little more extendable,
(also it doesn't run with `_test.rb` if the spec file was not found).

should work with `minitest` now once you specify the pattern in your settings.

sorry guys it took so long to address this 😞

cc @contentfree @iv-mexx

**Comment by noku** [comment]
@connorshea sorry it is not intuitive, currently to enable minitest testing I think you should specify two options: 

- `ruby.specPattern: "test"` (which will look for `_test`) and 
- `ruby.specCommand: ...` (command by which you run a minitest file).

most probably a better implementation will be to add a new `minitest` option for `"ruby.specGem"` which will infer those two options.

I will create a new PR that will do that.

**Comment by connorshea** [comment]
I set `"ruby.specCommand": "bundle exec rails test"` (it'd be `"ruby.specCommand": "bundle exec rake test"` for anyone on Rails versions before 5.0) and that made some tests work, unfortunately this isn't true of system tests because rails runs them separately using `rails test:system`. I'm not really sure why that happens or how to fix that 🤔 

Regardless, thank you :)

**Comment by marcelolx** [comment]
Just to someone that can come to this issue, the rails task `rails test:system` is made to run all system tests, if do you want to run a specific system test with this extension it should work with `rails test file_name.rb` in the same way unit tests work. 

My config 
```json
{
  "ruby.specCommand": "./bin/rails test",
  "ruby.specPattern": "test",
}
```` 

And thanks for this extension, I can't live without it anymore.

**Pull request merged**
